-- --------------------------------------------------------
-- 1. EXISTING TABLE: matches
-- (Reconstructed from codebase usage. Do not run if already exists.)
-- --------------------------------------------------------
create table if not exists matches (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone default now(),
  
  -- Player Info
  player1_address text,
  player2_address text,
  player1_steam text,
  player2_steam text,
  
  -- Match State
  status text default 'LOBBY', -- 'LOBBY', 'DEPOSITING', 'LIVE', 'COMPLETE'
  winner_address text,
  
  -- Blockchain / Payout
  contract_match_id text, -- ID from the Smart Contract
  payout_status text default 'PENDING' -- 'PENDING', 'PROCESSING', 'PAID', 'FAILED'
);

-- --------------------------------------------------------
-- 2. NEW TABLE: game_servers (For DatHost Pool)
-- (RUN THIS IN SUPABASE DASHBOARD)
-- --------------------------------------------------------
create table if not exists game_servers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  
  -- DatHost Info
  dathost_id text not null, -- The ID from DatHost (e.g., "65a1b2c3...")
  name text not null,       -- e.g., "Server A"
  ip text not null,         -- e.g., "1.2.3.4"
  port int not null,        -- e.g., 27015
  
  -- Pool Status
  status text default 'FREE', -- 'FREE', 'BUSY', 'OFFLINE'
  current_match_id uuid references matches(id), -- If BUSY, which match is it serving?
  
  -- Health Check
  last_heartbeat timestamp with time zone default now()
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table game_servers enable row level security;

-- Policy: Allow anyone to read (for now, to find a server)
create policy "Public Read" on game_servers for select using (true);

-- Policy: Allow Service Role (Backend) to update
-- (RLS is usually bypassed by Service Role anyway)
