-- Add ready check columns
ALTER TABLE matches ADD COLUMN IF NOT EXISTS p1_ready BOOLEAN DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS p2_ready BOOLEAN DEFAULT FALSE;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS ready_started_at TIMESTAMPTZ;
